### ISSUE TITLE
XMPP compatibility?

### ISSUE THREAD

**Issue by haansn08** [ietf-wg-mimi/mimi-protocol#40]
I feel like it's a missed opportunity by the MIMI WG to essentially ignore the prior art created with the XMPP standard and make no effort to be compatible with the existing XMPP internet standard.

I'm not sure why an entirely new transport protocol and message format that is not compatible with XMPP is being considered, instead of a XMPP protocol extension for MLS.

The advantages of Matrix were eventual consistency and more decentralized rooms, but the protocol proposal makes no mention of those features and the scaling issues Matrix has show that they're probably a bad idea too. Is it really worth breaking compatibility with XMPP just to replace XML with JSON?

**Comment by turt2live** [comment]
*For the record: I'm directly affiliated with Matrix as a Spec Core Team member.*

The MIMI charter mentions XMPP as a prior attempt to achieve interoperability, though implies that it's insufficient in some way. MIMI is aiming to *learn from* XMPP rather than implement XMPP. I'm not sure the concerns regarding XMPP have been enumerated, though this issue may be a good place to cover some of them as they relate to the protocol document specifically. 

The protocol document's purpose is to be as compatible as possible with existing messaging providers, which inherently includes compatibility with existing messaging(-ish) protocols too. The document does *not* use JSON or XML, and indeed doesn't have features that Matrix does either. This doesn't make it incompatible, however, as that would be counter to the point of MIMI. Both Matrix and XMPP can interact with MIMI through this protocol with relative ease, and should feel like that's in fact possible. 

For Matrix, initial compatibility would be defining a room version which is capable of representing MIMI's policies. Openly available exploration into some of the ideas MIMI has for policy are underway as [MSC4056](https://github.com/matrix-org/matrix-spec-proposals/pull/4056), [MSC4049](https://github.com/matrix-org/matrix-spec-proposals/pull/4049), [MSC4080](https://github.com/matrix-org/matrix-spec-proposals/pull/4080), etc. More rich compatibility might be extending MIMI RFCs when they exist, or further room version alterations, or both. None of this is important for MIMI to track directly, however. 

XMPP, alongside other existing messaging providers, may have to undergo a similar transition in their own systems. XMPP specifically might choose to write up an extension which is MIMI-compatible, or similar. Other messaging providers might implement a dual-stack service in their infrastructure which speaks MIMI on one side and their internal systems on the other. The protocol document's lack of history retention specifically gives the fire-and-forget protocols/providers a chance at interoperating, even if the network they're talking to supports history (like Matrix). 

Regarding Matrix's scalability briefly, it's worth noting that many of the concerns folks have are largely with the organic implementations rather than the protocol. The protocol requires very little to be persisted, though those organic implementations definitely are persist-heavy. As the network grows, the server implementations will become more efficient as well. Regardless, the protocol document being discussed here has been specifically designed with scalability in mind, particularly for the billions of users scenario.

Overall, I feel as though the level of compatibility we've reached in this document is sufficient for what MIMI hopes to achieve. Existing providers are able to use it relatively quickly, as are both Matrix and XMPP if they choose. The scalability of the protocol is unproven but feels correct, though may still need adjusting while implementations are written and evaluated. 

If you have specific concerns with the compatibility or scalability, I'm happy to address them here or with [proposed] edits to the document as required.

**Comment by haansn08** [comment]
> MIMI is aiming to learn from XMPP rather than implement XMPP.

I don't see how MIMI has learned from XMPP, in particular a good reason why MIMI is not implemented as an extension for XMPP in the first place.

The choice of HTTP as the transport protocol also strikes me as odd for an IM protocol, the streaming XML part of XMPP seems much more appropriate for IM providers.

**Comment by Alexis211** [comment]
> The choice of HTTP as the transport protocol also strikes me as odd for an IM protocol, the streaming XML part of XMPP seems much more appropriate for IM providers.

Here are some of the advantages of using a protocol based on HTTP that I see as a developer of distributed systems (note that this is my first time posting on discussions about the IETF MIMI effort, although I've been following it from afar for quite some time) :

- A streaming protocol using a single TCP connection would be subject to reliability issues such as head-of-line blocking (the situation where a dropped packet slows down the entire flow of data in a TCP connection, including unrelated traffic that could have gone through regardless), and the necessity for specific handling of restart logic when an existing connection is dropped/interrupted and a new connection has to be started. With HTTP, independent messages can be submitted through separate TCP connections, which are stateless by definition, and not subject to global head-of-line blocking.

- The reliability requirements on messaging applications match very well to the transactional nature of HTTP requests: when sending a message to a remote server using a PUT (or POST) request, a response code of 200 indicates that the recipient server has successfully received and stored the message, whereas any other result (error response code, connection reset, timeout, etc.) indicates that the message could not be transmitted, and should be queued for retry. Other features of IM applications, such as retrieving channel state (history, member list) or interacting with objects in any kind of ways generally map very well to HTTP semantics as well.

- By forcing the design of a protocol that uses separate, stateless HTTP requests for each message, we will naturally end up building a protocol that is idempotent, i.e. if we are not sure that a message was sent correctly, we just re-send it, and even if the first one did actually go through, the message will not be duplicated when the second requests is received as well. (This can be implemented using unique IDs on messages, and is an expected behavior of HTTP PUT requests).

- HTTP library support is excellent in most mainstream programming languages, and many developers are already familiar with HTTP semantics (which is not the case with XMPP), which could help MIMI to be adopted much more easily / much faster.

All in all, I am a strong believer in building a protocol that makes use of HTTP. The only downside I can see is that, technically, this would make for a slightly more heavyweight protocol than a streaming protocol using long-running statefull TCP connections. However I believe that these potential performance issues can generally be overcome by designing a protocol that is minimalistic / not bloated, and allowing for optimizations such as connection reuse, header compression, etc, all of which are features of the now-standard HTTP3. From what I've heard from a large public XMPP server that is currently running, the bottlenecks are not CPU or networking but rather on storage (for the loading of chat room history), so I believe the costs of using an HTTP-based protocol would be totally bearable and largely outweighted by the benefits which I mentioned above.

**Comment by tibequadorian** [comment]
As far as I understand and please correct me if I am wrong but I think MIMI tries to be as abstract as possible and only defines server-to-server communication whereas XMPP and Matrix also define client-to-server communication so this can also be implemented by proprietary messengers to be able to comply with interoperable messaging required by DMA in a standardized way while keeping their own way of handling client-to-server communication.

**Comment by tibequadorian** [comment]
>Is it really worth breaking compatibility with XMPP just to replace XML with JSON?

[This](https://datatracker.ietf.org/doc/draft-ietf-mimi-content/) draft currently states:
>we do not want to base64 encode body parts with binary media types (ex: images).  This rules out using JSON to carry the binary data.

**Comment by haansn08** [comment]
@Alexis211 

> A streaming protocol using a single TCP connection would be subject to reliability issues such as head-of-line blocking (the situation where a dropped packet slows down the entire flow of data in a TCP connection

Head-of-line blocking is not a very pressing issue for XMPP today, but even if it was there are much better options than establishing more TCP/SSL connections for every request/message like with HTTP, just to avoid head-of-line blocking. An updated XMPP spec with a message oriented transport protocol such as STCP would be nice and much more elegant than HTTP. Switching out the transport protocol also allows for backwards compatibility and avoids reinventing the wheel again.

> The reliability requirements on messaging applications match very well to the transactional nature of HTTP requests: when sending a message to a remote server using a PUT (or POST) request, a response code of 200 indicates that the recipient server has successfully received and stored the message

> By forcing the design of a protocol that uses separate, stateless HTTP requests for each message, we will naturally end up building a protocol that is idempotent, i.e. if we are not sure that a message was sent correctly, we just re-send it, and even if the first one did actually go through, the message will not be duplicated when the second requests is received as well. (This can be implemented using unique IDs on messages, and is an expected behavior of HTTP PUT requests).

You probably are looking for https://xmpp.org/extensions/xep-0198.html

> HTTP library support is excellent in most mainstream programming languages, and many developers are already familiar with HTTP semantics (which is not the case with XMPP), which could help MIMI to be adopted much more easily / much faster.

Since most IM users are trapped in large silos like WhatsApp today success will mostly depend on whether those large providers will adopt it or not. WhatsApp for example is already using a modified version of ejabberd internally, so XMPP federation would be the obvious choice for them. It's nice that there are masses of web developers out there that understand how HTTP works, but tbh there are very few companies that decide if MIMI will be successful. I think reinventing existing internet standards, instead of improving them is much more harmful to the goals of MIMI. XMPP is already a successful protocol - even if the original goal of universal federation has not been met. However this is due to the profit incentives of large IM providers (ofc interoperability is harder and as a "reward" is makes it easier for users to leave their platform). Publishing yet another IM protocol will do nothing to solve this problem and only introduce more fragmentation.

**Comment by ara4n** [comment]
Having just implemented Matrix interop with WA’s DMA APIs, I’m afraid that I can say with authority that they are *very* far removed from XMPP (as you would expect, given WhatsApp forked from XMPP and ejabberd before it even launched).

**Comment by haansn08** [comment]
@ara4n Can you share more details about the API? I cannot find any details on it. The most detailed account on the internals of WhatsApp I can find is this [article](https://mycodeplex.wordpress.com/2016/03/08/inside-of-whatsapp-part-1/) from 2016, which suggests that they use a static table to map XMPP keywords to single bytes and a lot of custom extensions.

**Comment by rohanmahy** [comment]
@haansn08 , first of all, I apologize to taking a long time to respond to this issue. 

I quite like the clean semantics of XMPP. It has clean layering; the very relevant distinction between `message`, `presence`, and `iq` stanzas; and it has inter-domain interoperability baked in. Most of largest messaging servers ran on XMPP at some time in the past. Some of them also permitted open-federation. 

So, why don't they use XMPP now? Open-federation became unsupportable due to spam and abuse, but that is not a reason to switch protocols (you can run an XMPP system that refuses to accept messages to or from most domains). 
The large vendors have volumes in the millions of messages per minute. They were some of the largest XMPP deployments and then transitioned to something else.

My understanding is that at some point the time spent parsing each stream to find the beginning and end of a stanza became a real bottleneck in these networks and made it challenging to implement what has become a standard high availability architecture, where a small number of ingress nodes forward to a much larger set of service nodes. 

Keeping track of which elements you are in, not to mention comments and CDATA blobs involve pretty non-trivial string processing if all you want to find is the start and end of a stanza. Chunking fixed length binary blobs is way easier and faster for an ingress node.

I wasn't familiar with XEP-0467, but it seems to focus on the client to server connection. I could imagine that a binary protocol that just delivers XMPP stanzas over mutual TLS or QUIC could already dramatically improve the ingress situation.

What else has changed since most instant messaging services ran on XMPP? End-to-end encryption. MIMI would not exist if it was not a requirement. Without it vendors could just gateway among protocols. E2EE means that the contents encrypted for the recipients need to be usable by the recipients. That means we need a standard content format, a standard encryption protocol (in this case MLS), compatible usage of that encryption, and a way to negotiation extensions. 

I would be delighted to see implementations of XMPP that use MLS, and I am willing to help implementers make that happen. I would also entertain using XMPP to exchange MLS-encrypted messages *in MIMI* if it includes a credible proposal to solve the high availability problem. 

That said, I think the semantics of consent, initial keying material, and the details of which MLS extensions are needed (ex: which external_senders are in a group and how they get there; how a welcomed client gets the ratchet tree) are much more pressing. Those questions need to get resolved regardless if MIMI transport happens over HTTP, XMPP, or something else.

Thanks,
-rohan

**Comment by mar-v-in** [comment]
Hi rohan,

I secured funding to specify and implement MLS in XMPP (see https://nlnet.nl/project/XMPP-MLS/). Compatibility of this specification with MIMI is important to me and the XMPP community. As of now, I assume that something along the lines of [draft-ietf-mimi-content](https://datatracker.ietf.org/doc/draft-ietf-mimi-content/) will be the MIMI payload format, which is fine for me (we can specify how it maps to XMPP and have an [XEP-0420](https://xmpp.org/extensions/xep-0420.html) envelope inside an additional part to accommodate for XMPP features not supported by MIMI itself where necessary).

As a client developer, I am personally not really involved with the selection of the transport protocol of MLS-encrypted MIMI messages - we can have server-side gateways to whatever MIMI decides to do.

As I understood, there was no interest within the MIMI WG to use a protocol based on and/or compatible with current XMPP specification, software and deployments and this is a fair decision. If there was a clear signal from MIMI WG that XMPP is desired to be used, I am certain that several community members would be willing to prioritize developments around that. But as many contributors to XMPP don't have a lot of resources they are willing to waste on this (if there is no intent from the MIMI WG to pick these things up, it would likely be wasted), you are unlikely to see large documents being prepared to promote the use of XMPP in MIMI.

**Comment by rohanmahy** [comment]
@mar-v-in 
I'm happy to hear that you have funding to write a XEP for MLS. I'm happy to help, and I would love the MIMI usage of MLS and the XEP to be compatible. Please DM me (IETF Slack, @rohanmahy on Wire, rohan.ietf@gmail.com ).

> If there was a clear signal from MIMI WG that XMPP is desired to be used, I am certain that several community members would be willing to prioritize developments around that. But as many contributors to XMPP don't have a lot of resources they are willing to waste on this (if there is no intent from the MIMI WG to pick these things up, it would likely be wasted), you are unlikely to see large documents being prepared to promote the use of XMPP in MIMI.

I think this is a bit of a chicken and egg problem. I think having an idea of how it would work at the bar-napkin or half-page outline level would be useful for the rest of the WG to even understand how it would be possible.

**Comment by Neustradamus** [comment]
To follow this important ticket about XMPP.
